apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
      - name: pod-2
        image: 762146779104.dkr.ecr.us-east-1.amazonaws.com/serverless:nodejsbasic-latest
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pod-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pod-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pod-secret
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: pod-secret
              key: DB_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer  
  selector:
    app: pod-2
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8000
