apiVersion: apps/v1
kind: Deployment
metadata:
  name: fargate-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-1
  template:
    metadata:
      labels:
        app: pod-1
    spec:
      nodeSelector:
        eks.amazonaws.com/fargate-profile: fargate-profile
      containers:
        - name: fargate-app
          image: 567891620707.dkr.ecr.us-east-1.amazonaws.com/lks-ecr-imannuel:showip-latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fargate-service
spec:
  type: LoadBalancer
  selector:
    app: fargate-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
