apiVersion: apps/v1
kind: Deployment
metadata:
  name: fargate-pods
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      nodeSelector:
        eks.amazonaws.com/fargate-profile: demo-fargate
      containers:
        - name: fargate-app
          image: 567891620707.dkr.ecr.us-east-1.amazonaws.com/lks-ecr-imannuel:showip-latest
          ports:
            - containerPort: 5000
