apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  type: ClusterIP
  selector:
    app: app 
  ports:
    - name: showip
      protocol: TCP
      port: 80
      targetPort: 5000  
    - name: nodejscrud
      protocol: TCP
      port: 80
      targetPort: 8000 
 