name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install

    - name: Build ZIP for Deployment
      run: |
        zip -r nodejsbasic.zip . -x "node_modules/*"

    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: showipjs
        path: showipjs.zip


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: showipjs
    
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Upload ZIP to S3
      run: |
        aws s3 cp showipjs.zip s3://${{ secrets.S3_BUCKET_NAME }}/showipjs.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
        EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        VERSION_LABEL="${{ github.sha }}-$(date +%s)"
        aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.EB_APP_NAME }} \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=showipjs.zip
        aws elasticbeanstalk update-environment \
          --environment-name ${{ secrets.EB_ENV_NAME }} \
          --version-label $VERSION_LABEL
